import glob
import pandas as pd

from pytz import timezone
from datetime import datetime

# Helper function                                                                                
def get_current_time():
    return datetime.now(timezone('Asia/Hong_Kong')).strftime('%Y-%m-%d_%H-%M-%S-%f')[:-3]

class Decoder(object):
	@staticmethod
	def get_strategy_status(output_dir):
		# This function decodes the log file generated by backtest_pair.py
		# Returns a dataframe

		# get the path of the log file
		log_path = glob.glob(output_dir + "/*.log")[0]

		# hardcoded keyword
		keyword = "[strategy-status]"

		match_lines = []
		with open(log_file_path, "r") as file:
			for line in file:
				idx = line.find(keyword)
				if idx >= 0:
					match_lines.append(line[idx:])

		dict_list = []
		for line in match_lines:
			dict_list.append(eval(line[len(keyword) + 2: -1]))

		return pd.DataFrame(dict_list)

